// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirectoryDialog() {
  return window['go']['app']['ImageApp']['OpenDirectoryDialog']();
}

export function OpenMultipleFilesDialog() {
  return window['go']['app']['ImageApp']['OpenMultipleFilesDialog']();
}

export function ProcessImages(arg1) {
  return window['go']['app']['ImageApp']['ProcessImages'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['ImageApp']['Startup'](arg1);
}
