// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function OpenDirectoryDialog():Promise<string>;

export function OpenMultipleFilesDialog():Promise<Array<app.FileInfo>>;

export function ProcessImages(arg1:app.ProcessImagesOptions):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
